name: test
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO: Support ubuntu
        os: [ubuntu-latest, windows-latest]
        # os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up GCC
        if: startsWith(matrix.os, 'ubuntu')
        uses: egor-tensin/setup-gcc@v1
        with:
          platform: x64

      - name: Make ndstool executable
        if: startsWith(matrix.os, 'ubuntu')
        run: chmod +x utils/ndstool

      - name: Set up MinGW
        if: startsWith(matrix.os, 'windows')
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      
      - name: Compile BLZ compression tool
        run: gcc blz.c -o blz
        working-directory: utils

      - name: Install pip dependencies
        run: |
          pip install gdown ndspy

      - name: Build
        run: |
          gdown https://drive.google.com/uc?id=${{ secrets.GOOGLE_DRIVE_FILE_ID }}
          python unpack.py
          python build.py
