name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      
      - name: Compile BLZ compression tool
        run: gcc blz.c -o blz
        working-directory: utils

      - name: Install pip dependencies
        run: |
          pip install gdown ndspy

      - name: Build
        run: |
          gdown https://drive.google.com/uc?id=${{ secrets.GOOGLE_DRIVE_FILE_ID }}
          python unpack.py
          python build.py
